export const MessageEvent = {
  ATTRIBUTE_CHANGE: 'ATTRIBUTE_CHANGE',
  CALL: 'CALL',
  CALL_RESPONSE: 'CALL_RESPONSE',
  CUSTOM_EVENT: 'CUSTOM_EVENT',
  ERROR: 'ERROR',
  EVENT: 'EVENT',
  INIT: '__INIT__',
  NAVIGATE: 'NAVIGATE',
  READY: '__READY__',
  STATE_CHANGE: 'STATE_CHANGE',
} as const;
